// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var Generator, yeoman,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  yeoman = require('yeoman-generator');

  Generator = (function(_super) {
    __extends(Generator, _super);

    function Generator() {
      var args, _base;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      (_base = args[0])[0] || (_base[0] = 'rewind-angular');
      Generator.__super__.constructor.apply(this, args);
    }

    Generator.prototype.showName = function() {
      return console.log(this.name);
    };

    return Generator;

  })(yeoman.generators.NamedBase);

  module.exports = Generator;

}).call(this);
